title: M. Andrew Eick
baseURL: 'https://www.eick.com/'
languageCode: en-us
DefaultContentLanguage: en
paginate: 10
copyright: © Copyright notice
disableAliases: true
enableRobotsTXT: true

taxonomies:
  tag: tags

# Some bugs related to 404 template https://github.com/gohugoio/hugo/issues/7603
disableKinds:
  - '404'
# googleAnalytics: UA-PROPERTY_ID
sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5