title: M. Andrew Eick
baseURL: 'https://www.eick.com/'
languageCode: en-us
DefaultContentLanguage: en
paginate: 5
copyright: © Copyright notice
disableAliases: true
enableRobotsTXT: true

taxonomies:
  tag: tags

mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes:
      - ""
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - tnd_redirects_netlify