photo_api:
  pretty_permalink: true
  
# ###############
# PLAUSIBLE
#
# To exclude pages from tracking:
# Any pages listed in this format, comma-separated, with asterisks to indicate 
# unspecified regions of the pathname, will not be counted in your Plausible dashboard.
# 
# "/blog4, /rule/*, /how-to-*, /*/admin, /*/priv/*, /more-paths-here"
#
# All entries must begin with a /, and should not include the trailing slash as we 
# account for this automatically.
#
# Asterisks (*) expand to any stretch (of length >=0) of the page path and can be on 
# either end or in the middle of any entry, but cannot be in the place of slashes.
# Double asterisks (**) expand to any stretch (of length >=0) of the page path, 
# can be on either end or in the middle of any entry, and can represent any 
# characters, even slashes.
#
# https://plausible.io/docs/excluding-pages#2-add-the-pages-youd-like-to-exclude-from-being-tracked
#
# ###############
plausible: eick.com
plausible_exclude: "/media-test, /.netlify, /photos/page/*"
# ###############
# TND SEO
# https://github.com/theNewDynamic/hugo-module-tnd-seo#settings
# ###############
tnd_seo:
  jsonld: true
  enable_follow: true
  disable_title: false

# ###############
# TND STYLES
# https://github.com/theNewDynamic/hugo-module-tnd-styles#fonts
# ###############
tnd_styles:
  fonts:
    - family: Play
      style: normal
      weight: 400
      file: fonts/files/play-v11-latin-regular
    - family: Play
      style: normal
      weight: 700
      file: fonts/files/play-v11-latin-700

# ###############
# TND SCRIPTS
# https://github.com/theNewDynamic/hugo-module-tnd-scripts
# ###############
tnd_scripts:
  scripts:
    - name: main
      path: /js/index.js
    - name: audioplayer
      path: /js/audioplayer.js
    - name: mux
      path: /js/mux.js
    - name: cloudflare-media
      path: /js/cloudflare_media.js
# ###############
# TND MEDIA
# https://github.com/theNewDynamic/hugo-module-tnd-media#settings
# If used in combination with imgix:
# https://github.com/theNewDynamic/hugo-module-tnd-imgix#settings
# ###############
tnd_media:
  storage: static
  imgix:
    domain: edc.imgix.net
    defaults:
      auto: format
      ch: Width,DPR
      q: 95

# ###############
# TND SOCIALS
# https://github.com/theNewDynamic/hugo-module-tnd-socials#configure
# ###############
tnd_socials:
  services:
  - name: github
    handle: 'https://github.com/andreweick'
  - name: rss
    handle: https://www.eick.com/index.xml

# ###############
# TND REDIRECTS
# https://github.com/theNewDynamic/hugo-module-tnd-redirects#api
# ###############
tnd_redirects:
  use_aliases: true
  rules:
  # Following rule for production
  # - origin: https://www-eick-com.netlify.app/*
  #   target: https://www.eick.com/:splat
  #   code: 301
  #   force: true

# ###############
# TND HEADERS
# https://github.com/theNewDynamic/hugo-module-tnd-headers#adding-custom-headers
# ###############
tnd_headers:
  groups:
    - headers:
      - field: Content-Security-Policy
        value: upgrade-insecure-requests
      - field: Strict-Transport-Security
        value: max-age=15768000
      - field: X-Xss-Protection
        value: 1; mode=block
      - field: X-Frame-Options
        value: DENY
      - field: X-Content-Type-Options
        value: nosniff
      - field: Referrer-Policy
        value: strict-origin-when-cross-origin
      - field: Feature-Policy
        value: camera 'none'; geolocation 'none'; microphone 'none';


tnd_search:
  service: meili
  instantsearch:
    indexName: default
    appId: https://search.eick.ws
    apiKey: 71dea55ca64952406e4685744e437840e5b97dc5b5b65c080fd67d2deab445c4
    startEmpty: true
    widgets:
    - name: searchBox
      autofocus: true
      placeholder: 'Search'
      showSubmit: false
      showReset: false
      showLoadingIndicator: false
      classes:
        root: 'px-2'
        reset: 'hidden'
        input: 'hide-clear border block b-white w-full py-2 px-4 text-3xl leading-5 text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 border-opacity-0 focus:ring-offset-2 focus:ring-offset-indigo-600 focus:ring-white focus:border-white'
    - name: menu
      js: menu
      attribute: tags
      classes:
        root: mb-4 px-4
        count: hidden
        list: flex flex-wrap justify-start list-reset
        item: text-sm px-2 py-1 text-black mr-1
        link: text-black no-underline
    - name: hits
      templates:
        item: |
          <a class="flex items-center block p-2 font-bold text-black no-underline border-b border-black group hover:bg-grey-light min-h-24" href="{{ permalink }}">
            <div>
              <div class="text-sm font-normal leading-tight group-hover:text-white">
              {{type}}
              </div>
              {{title}}
            </div>
          </a>
        empty: |
          <span class="block px-8 py-2 border-b border-black">No results</span>
      classes:
        root: 'px-4'
        list: 'list-reset'
    - name: pagination
      classes:
        root: py-2 mt-8 text-black px-4
        list: flex items-center list-reset flex-wrap justify-center
        item: text-xs text-black inline-block border shadow align-middle mb-2 lg:mb-0 mx-1 py-1 px-2 md:py-2 md:px-4 hover:bg-gray-200
        link: text-current no-underline
        selectedItem: no-underline