
production: false
bust_css_cache: true
show_drafts: true
future: true
unpublished: true

mediaUrlRoot: "http://stage.media.eick.us"

destination: _staging

defaults:
  -
   scope:
    path: ''
   values:
    layout: post
    sitemap: false
