mediaUrlRoot: "http://media.eick.us"

# dev options (true/false)
# if site is in production, 'production: true'
production: false
bust_css_cache: true

defaults:
  -
   scope:
    path: ''
   values:
    layout: post
    allow-robots: false
