title:   Andrew Eick
description: "Head in the clouds, feet in the dirt."
bio: "Andrew Eick is a technologist dedicated to crafting scientific innovation into practical solutions for the Intelligence Community"
url: http://eick.us
# basedir:          "/"
mediaUrlRoot: "https://media.eick.us"
image_path: '/assets/img/'

# gems:
  #- jekyll-sitemap


plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
port: 4001
timezone:    America/New_York
future:      true
include: ['_pages', '.htaccess']
exclude:
  - readme.md
  - license.md
  - gemfile
  - Gemfile.lock
  - links.jsonp
  - CNAME
  - rakefile
  - bower.json
  - gulp
  - gulpfile.js
  - package.json
  - flags.md
  - bower_components
  - node_modules
permalink: pretty
keep_files: ['media']





# dev options (true/false)
# if site is in production, 'production: true'
production: true
bust_css_cache: true
show_drafts: false
future: false
unpublished: false

# options (data)
google_analytics_id: UA-320642-1
typekit_id: qur4ysq


collections:
 cv:
  collection_name: "CV"
  output: true
  description: "About Andrew Eick"
  permalink: /:collection/:path/

# source: content
# TODO: Set default layouts for posts, pages, and arguendo, and ipsos

defaults:
  -
   scope:
    path: ''
   values:
    layout: post


compress_html:
#  ignore:
#    envs: [development]
  profile: false
