theme: ananke
baseURL: 'https://www.eick.com/'
languageCode: en-us
title: M. Andrew Eick
paginate: 5
copyright: © Copyright notice
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
params:
  subtitle: 'If A, then B; B; therefore A'
  avatar: 'https://secure.gravatar.com/avatar/335dc7f83bbef5faacc41a687534c09f'
  disableDisqusTypes:
    - page
  featherIconsCDN: true
  mode: auto
  social:
    - name: Github
      icon: github
      url: 'https://github.com/andreweick'
    - name: RSS
      icon: rss
      url: /index.xml
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
taxonomies:
  tag: tags
module:
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
