#theme = "hugo-ink"
theme = "ananke"

baseURL = "https://www.eick.com/"
languageCode = "en-us"
title = "M. Andrew Eick"
paginate = 5

copyright = "© Copyright notice"

[params]
	subtitle = "If A, then B; B; therefore A"

	# Optional 64x64 avatar image.
	avatar = "https://secure.gravatar.com/avatar/335dc7f83bbef5faacc41a687534c09f"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/andreweick"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
   tag = "tags"