title: M. Andrew Eick
baseURL: 'https://www.eick.com/'
languageCode: en-us
DefaultContentLanguage: en
themesDir: components
paginate: 5
copyright: © Copyright notice

enableRobotsTXT: true
theme:
  - layouts-base
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: true
params:
  subtitle: 'If A, then B; B; therefore A'
  avatar: 'https://secure.gravatar.com/avatar/335dc7f83bbef5faacc41a687534c09f'
  disableDisqusTypes:
    - page
  featherIconsCDN: true
  mode: auto
  social:
    - name: Github
      icon: github
      url: 'https://github.com/andreweick'
    - name: RSS
      icon: rss
      url: /index.xml
menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: All posts
      url: /posts
      weight: 2
    - name: About
      url: /about
      weight: 3
    - name: Tags
      url: /tags
      weight: 4
taxonomies:
  tag: tags
module:
  imports:
    - path: github.com/theNewDynamic/hugo-module-tnd-netlifycms
mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes:
      - ""
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR