title: Andrew Eick
themesDir: components
theme:
  - layouts-base
DefaultContentLanguage: en
MetaDataFormat: yaml
buildFuture: true
baseURL: "https://www.eick.com"
enableRobotsTXT: true
paginate: "5"
googleAnalytics: ""
languageCode: en-us
blackfriday:
  fractions: false
taxonomies:
  series: series
  tag: tags
params:
  description: The Personal Website of Andrew Eick
  logo: ""
mediaTypes:
  text/netlify:
    delimiter: ""
    suffixes:
      - ""
outputFormats:
  HEADERS:
    baseName: _headers
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
  REDIR:
    baseName: _redirects
    isPlainText: true
    mediatype: text/netlify
    notAlternative: true
outputs:
  home:
    - HTML
    - HEADERS
    - REDIR
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About
      url: /about/
      weight: 2
    - identifier: notes
      name: notes
      url: /notes/
      weight: 4
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 3
