[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "10.13.0"
  HUGO_VERSION = "0.73.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
[context.split1]
command = "hugo --gc --minify --enableGitInfo"

[context.split1.environment]
HUGO_ENV = "production"
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
[context.next.environment]
HUGO_ENABLEGITINFO = "true"
