[build]
publish = "public"
command = "hugo --minify"

[build.environment]
  GO_VERSION = "1.14"
  NODE_VERSION = "15.4.0"
  HUGO_VERSION = "0.89.4"

[functions]
  directory = "functions"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --minify -D -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy]
command = "hugo --minify -b $DEPLOY_URL"
[context.branch-deploy.environment]
HUGO_ENV = "staging"

[[plugins]]
  package = "./build/netlify-plugin-s3photo"
  [plugins.inputs]
  contentDir = "remote/s3"
  entryLimit = 100

[[context.deploy-preview.plugins]]
package = "@netlify/plugin-local-install-core"
[[context.production.plugins]]
package = "@netlify/plugin-local-install-core"

[dev]
  functions = "functions"
  publish = "public"
  framework = "#custom"
  command = "npm run start"
  port = 8888
  targetPort = 1313
