[build]
publish = "public"
command = "cd remote && hugo && cd .. && hugo"

[build.environment]
  GO_VERSION = "1.16.5"
  NODE_VERSION = "15.4.0"
  HUGO_VERSION = "0.91.0"

[functions]
  directory = "functions"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "cd remote && hugo && cd .. && hugo --minify -D -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
HUGO_ENV = "staging"

[context.branch-deploy]
command = "cd remote && hugo && cd .. && hugo --minify -b $DEPLOY_URL"
[context.branch-deploy.environment]
HUGO_ENV = "staging"

[dev]
  functions = "functions"
  publish = "public"
  framework = "#custom"
  command = "npm run start"
  port = 8888
  targetPort = 1313
