name: Build & Publish

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.101.0"
          extended: true
      - name: Build photolist
        run: cd remote && pwd && hugo
      - name: Build site
        run: cd .. && pwd && hugo
    # - name: Publish to Workers Sites
    #   uses: cloudflare/wrangler-action@1.3.0
    #   with:
    #     apiToken: ${{ secrets.CF_API_TOKEN }}
